apiVersion: v1
kind: Service
metadata:
  name: svc-dka
spec:
  type: NodePort  #3 types of services NodePort, Loadbalancer, clusterip
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  selector:
    app: dka
